### ISSUE TITLE
The hyperparameters to reproduce the results

### ISSUE THREAD

**Issue by EddieBio** [EperLuo/scDiffusion#1]
Hi,

Could you please provide the hyperparameters for the reproduction of the results? I have run your train.sh, however, I cannot reproduce the unconditional generation results. Beside, different scripts contain different model paths although they all aim for unconditional generation. For example, the SCC is 0.76 and the PCC is 0.71, the UMAP figure does not suggest that the real dataset can be covered by the generated dataset, and the ACC of RF is 1.0.
<img width="258" alt="image" src="https://github.com/EperLuo/scDiffusion/assets/160054312/47a288a7-624d-4f3e-9ec5-6e4a09159f85">
![image](https://github.com/EperLuo/scDiffusion/assets/160054312/ceb3e436-3b0c-40ab-96c5-4d888e41a638)

Thanks.

**Comment by EperLuo** [comment]
Hi, sorry for the late reply.
The hyperparameters used in this code repository are the same as we used when conducting our experiments. The problem might lie in insufficient training. We trained this version of Autoencoder and Diffusion model for 80e4 steps. You could try to train the model for a longer time and see if the results are different.
Besides, we've made some major changes to the original model, which reduced the time for training the Autoencoder and diffusion model significantly. You could try this new training pipeline if you are interested.

**Comment by EddieBio** [comment]
I appreciate your kind response. However, I found that the figure 2b in your manuscript is generated without the guidance of the classifier. However, this umap figure in your script_diffusion_umap.ipynb is generated by the conditional generation strategy. 
<img width="982" alt="image" src="https://github.com/EperLuo/scDiffusion/assets/160054312/f9ea6b0a-086b-4244-8c23-bb5f6f361222">

**Comment by Sbs12** [comment]
Hello, I have encountered the same problem. Can your unconditional generation effect achieve the effect described in the article?

**Comment by aawdeh** [comment]
Hello, I encountered the same problem reported above. The actual and predicted values do not match after training on the Tabula Muris dataset. 

I trained the autoencoder for 300,000 steps and the diffusion model for 800,000 steps. I also experimented with fewer training steps, but the mismatch persists regardless.
