### ISSUE TITLE
Regarding the training of the classifier

### ISSUE THREAD

**Issue by jingfengou** [EperLuo/scDiffusion#3]
Did you incorporate the noise from the diffusion forward process during its training? After I added this noise, the classifier became difficult to train. I suspect that the noise is too large arnd masks the features of the original data.

**Comment by EperLuo** [comment]
Hi! I did add the noise from the diffusion forward process during the training of classifier, but I only added noise from the first 500 steps (totally 1000 steps), which is relatively small and do not masks to much of the data feature. And the guidance will start from the 500th step during inference.

**Comment by Sbs12** [comment]
Hello, can your unconditional generation effect achieve the effect described in the article?
